controller_list:
  - name: fake_world_controller
    joints:
      []
  - name: fake_rotation_controller
    joints:
      - joint1
  - name: fake_arm_controller
    joints:
      - joint2
      - joint3
      - joint4
  - name: fake_gripper_controller
    joints:
      - joint5